rules:
  ActionCallsInLoop:
    severity: error
  APIVersion:
    severity: error
  AutoLayout:
    severity: error
  CopyAPIName:
    severity: error
  CyclomaticComplexity:
    severity: error
  DMLStatementInLoop:
    severity: error
  DuplicateDMLOperation:
    severity: error
  FlowDescription:
    severity: error
  FlowName:
    severity: error
  GetRecordAllFields:
    severity: error
  HardcodedId:
    severity: error
  HardcodedUrl:
    severity: error
  InactiveFlow:
    severity: error
  MissingFaultPath:
    severity: error
    suppressions:
      - "Nebula__FlowLogEntry"
  MissingNullHandler:
    severity: error
  ProcessBuilder:
    severity: error
  RecursiveAfterUpdate:
    severity: error
  SameRecordFieldUpdates:
    severity: error
  SOQLQueryInLoop:
    severity: error
  TriggerOrder:
    severity: error
    disabled: true
  UnconnectedElement:
    severity: error
  UnsafeRunningContext:
    severity: error
  UnusedVariable:
    severity: error
exceptions: